---
name: Build

on:
  - push
  - pull_request

jobs:
  Linux:
    container:
      image: devkitpro/devkita64:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          apt-get --yes update
          apt-get --yes install build-essential python-pip zstd

      - name: Install DKP build dependencies
        run: |
          curl --location --remote-name-all \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/linux/x86_64/hactool-1.4.0-3-x86_64.pkg.tar.xz
          dkp-pacman --noconfirm --upgrade *.pkg.tar.*

      - name: Install Python build dependencies
        run: |
          pip install lz4 pycryptodome

      - name: Ensure GITHUB_WORKSPACE directory is considered safe
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Build
        run: |
          make -j3

      # - name: Upload Fusée
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Fusée
      #     path: out/nintendo_nx_arm64_armv8a/release/fusee.bin
      #
      # - name: Upload Atmosphère
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Atmosphère
      #     path: out/nintendo_nx_arm64_armv8a/release/atmosphere*.zip
  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSYS2 
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            base-devel
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-python2
            mingw-w64-x86_64-python2-pip
            zip
          msystem: MSYS
          update: true

      - name: Add DKP package repositories
        run: |
          # tee --append /etc/pacman.conf << EOF

          # [dkp-libs]
          # Server = https://pkg.devkitpro.org/packages

          # [dkp-windows]
          # Server = https://pkg.devkitpro.org/packages/windows/\$arch/
          # EOF
        shell: msys2 {0}

      - name: Install DKP keyring
        run: |
          curl \
            --location \
            --remote-name \
            https://pkg.devkitpro.org/devkitpro-keyring.pkg.tar.xz
          pacman --noconfirm --upgrade devkitpro-keyring.pkg.tar.xz
        shell: msys2 {0}

      - name: Install DKP build dependencies
        run: |
          # pacman --noconfirm --sync --refresh --sysupgrade --needed --overwrite \
          #   devkitARM \
          #   devkitA64 \
          #   devkitarm-rules \
          #   hactool \
          #   switch-dev \
          #   switch-glm \
          #   switch-libjpeg-turbo

          curl --location --remote-name-all \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/deko3d-0.4.0-1-any.pkg.tar.xz \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/devkita64-cmake-1.1.2-1-any.pkg.tar.zst \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/devkita64-rules-1.1.1-1-any.pkg.tar.zst \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/devkitarm-crtls-1.2.2-1-any.pkg.tar.zst \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/devkitarm-rules-1.5.0-2-any.pkg.tar.zst \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/dkp-cmake-common-utils-1.5.1-1-any.pkg.tar.zst \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/libnx-4.4.2-1-any.pkg.tar.zst \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/switch-cmake-1.5.0-1-any.pkg.tar.xz \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/switch-examples-20201219-1-any.pkg.tar.xz \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/switch-glm-0.9.9.7-2-any.pkg.tar.xz \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/switch-libjpeg-turbo-2.1.2-2-any.pkg.tar.xz \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/switch-pkg-config-0.28-4-any.pkg.tar.xz \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/windows/x86_64/devkit-env-1.0.1-2-any.pkg.tar.zst \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/windows/x86_64/devkitA64-gdb-13.2-1-x86_64.pkg.tar.zst \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/windows/x86_64/devkitA64-r22.1-1-x86_64.pkg.tar.zst \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/windows/x86_64/devkitARM-gdb-13.2-1-x86_64.pkg.tar.zst \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/windows/x86_64/devkitARM-r61-4-x86_64.pkg.tar.zst \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/windows/x86_64/general-tools-1.4.4-1-x86_64.pkg.tar.zst \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/windows/x86_64/hactool-1.4.0-3-x86_64.pkg.tar.xz \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/windows/x86_64/switch-tools-1.12.0-1-x86_64.pkg.tar.xz \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/windows/x86_64/uam-1.1.0-2-x86_64.pkg.tar.xz

          pacman --noconfirm --upgrade *.pkg.tar.*
        shell: msys2 {0}

      - name: Install Python build dependencies
        run: |
          /mingw64/bin/pip2 install lz4 pycryptodome
        shell: msys2 {0}

      - name: Ensure GITHUB_WORKSPACE directory is considered safe
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
        shell: msys2 {0}

      - name: Build
        run: |
          source /etc/profile.d/devkit-env.sh
          mv /mingw64/bin/python.exe /mingw64/bin/python.backup.exe
          ln -s /mingw64/bin/python2.exe /mingw64/bin/python.exe
          export PATH=$PATH:/mingw64/bin
          make -j3
        shell: msys2 {0}

      # - name: Upload Fusée
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Fusée
      #     path: out/nintendo_nx_arm64_armv8a/release/fusee.bin
      #
      # - name: Upload Atmosphère
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Atmosphère
      #     path: out/nintendo_nx_arm64_armv8a/release/atmosphere*.zip
