---
name: Build

on:
  - push
  - pull_request

jobs:
  Linux:
    container:
      image: devkitpro/devkita64:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          apt-get --yes update
          apt-get --yes install build-essential python-pip zstd

      - name: Install DKP build dependencies
        run: |
          curl --location --remote-name-all \
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/linux/x86_64/hactool-1.4.0-3-x86_64.pkg.tar.xz
          dkp-pacman --noconfirm --upgrade *.pkg.tar.*

      - name: Install Python build dependencies
        run: |
          pip install lz4 pycryptodome

      - name: Ensure GITHUB_WORKSPACE directory is considered safe
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Build
        run: |
          make -j3

  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSYS2 
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            base-devel
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-python2
            mingw-w64-x86_64-python2-pip
            zip
          msystem: MSYS
          update: true

      - name: Add DKP package repositories
        run: |
          tee --append /etc/pacman.conf << EOF

          [dkp-libs]
          Server = https://web.archive.org/web/https://pkg.devkitpro.org/packages

          [dkp-windows]
          Server = https://web.archive.org/web/https://pkg.devkitpro.org/packages/windows/\$arch/
          EOF
          sed -i \
            -e "s/ParallelDownloads.*/ParallelDownloads = 1/g" \
            -e "s/\[options\]/[options]\nDisableDownloadTimeout/g" \
            /etc/pacman.conf
        shell: msys2 {0}

      - name: Install DKP keyring
        run: |
          curl \
            --location \
            --remote-name \
            https://pkg.devkitpro.org/devkitpro-keyring.pkg.tar.xz
          pacman --noconfirm --upgrade devkitpro-keyring.pkg.tar.xz
        shell: msys2 {0}

      - name: Install DKP build dependencies
        run: |
          pacman --noconfirm --sync --refresh --needed \
            devkitARM \
            devkitARM-gdb \
            hactool \
            switch-dev \
            switch-glm \
            switch-libjpeg-turbo
        shell: msys2 {0}

      - name: Install Python build dependencies
        run: |
          /mingw64/bin/pip2 install lz4 pycryptodome
        shell: msys2 {0}

      - name: Ensure GITHUB_WORKSPACE directory is considered safe
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
        shell: msys2 {0}

      - name: Build
        run: |
          source /etc/profile.d/devkit-env.sh
          mv /mingw64/bin/python.exe /mingw64/bin/python.backup.exe
          ln -s /mingw64/bin/python2.exe /mingw64/bin/python.exe
          export PATH=$PATH:/mingw64/bin
          make -j3
        shell: msys2 {0}
