---
name: Build

on:
  - push
  - pull_request

jobs:
  Linux:
    container:
      image: devkitpro/devkita64:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          echo $PATH
          apt-get --yes update
          apt-get --yes dist-upgrade

      - name: Update DKP package servers
        run: |
          sed --in-place \
            --expression 's# https://pkg.devkitpro.org# https://web.archive.org/web/https://pkg.devkitpro.org#g' \
            /opt/devkitpro/pacman/etc/pacman.conf

      - name: Install DKP build dependencies
        run: |
          dkp-pacman --needed --noconfirm --refresh --sync --sysupgrade hactool

      - name: Ensure GITHUB_WORKSPACE directory is considered safe
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Build
        run: |
          make --jobs $(nproc)
        shell: bash

  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2 
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            base-devel
            git
            mingw-w64-x86_64-python
            mingw-w64-x86_64-python-lz4
            mingw-w64-x86_64-python-pip
            mingw-w64-x86_64-python-pycryptodome
            mingw-w64-x86_64-toolchain
            zip
          msystem: MSYS
          update: true

      - name: Add DKP package repositories
        run: |
          tee --append /etc/pacman.conf << EOF

          [dkp-libs]
          Server = https://web.archive.org/web/https://pkg.devkitpro.org/packages

          [dkp-windows]
          Server = https://web.archive.org/web/https://pkg.devkitpro.org/packages/windows/\$arch/
          EOF
          sed -i \
            -e "s/ParallelDownloads.*/ParallelDownloads = 1/g" \
            -e "s/\[options\]/[options]\nDisableDownloadTimeout/g" \
            /etc/pacman.conf
        shell: msys2 {0}

      - name: Install DKP keyring
        run: |
          curl \
            --location \
            --remote-name \
            https://pkg.devkitpro.org/devkitpro-keyring.pkg.tar.xz
          pacman --noconfirm --upgrade devkitpro-keyring.pkg.tar.xz
        shell: msys2 {0}

      - name: Install DKP build dependencies
        run: |
          pacman --needed --noconfirm --refresh --sync --sysupgrade \
            devkitARM \
            devkitARM-gdb \
            hactool \
            switch-dev \
            switch-glm \
            switch-libjpeg-turbo
        shell: msys2 {0}

      - name: Ensure GITHUB_WORKSPACE directory is considered safe
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
        shell: msys2 {0}

      - name: Build
        run: |
          source /etc/profile.d/devkit-env.sh
          export PATH=$PATH:/mingw64/bin
          make -j3
        shell: msys2 {0}
