---
name: Build

on:
  - push
  - pull_request

jobs:
  Linux:
    container:
      image: devkitpro/devkita64:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/dependencies/install
        with:
          linux-dkp-package-urls: >-
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/linux/x86_64/hactool-1.4.0-3-x86_64.pkg.tar.xz

      - name: Ensure GITHUB_WORKSPACE directory is considered safe
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
        shell: bash {0}

      - name: Build
        run: |
          make -j3
        shell: bash {0}

  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/dependencies/install
        with:
          windows-dkp-package-urls: >-
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/linux/x86_64/hactool-1.4.0-3-x86_64.pkg.tar.xz
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/deko3d-0.4.0-1-any.pkg.tar.xz
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/devkita64-cmake-1.1.2-1-any.pkg.tar.zst
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/devkita64-rules-1.1.1-1-any.pkg.tar.zst
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/devkitarm-crtls-1.2.2-1-any.pkg.tar.zst
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/devkitarm-rules-1.5.0-2-any.pkg.tar.zst
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/dkp-cmake-common-utils-1.5.1-1-any.pkg.tar.zst
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/libnx-4.4.2-1-any.pkg.tar.zst
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/switch-cmake-1.5.0-1-any.pkg.tar.xz
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/switch-examples-20201219-1-any.pkg.tar.xz
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/switch-glm-0.9.9.7-2-any.pkg.tar.xz
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/switch-libjpeg-turbo-2.1.2-2-any.pkg.tar.xz
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/switch-pkg-config-0.28-4-any.pkg.tar.xz
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/windows/x86_64/devkit-env-1.0.1-2-any.pkg.tar.zst
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/windows/x86_64/devkitA64-gdb-13.2-1-x86_64.pkg.tar.zst
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/windows/x86_64/devkitA64-r22.1-1-x86_64.pkg.tar.zst
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/windows/x86_64/devkitARM-gdb-13.2-1-x86_64.pkg.tar.zst
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/windows/x86_64/devkitARM-r61-4-x86_64.pkg.tar.zst
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/windows/x86_64/general-tools-1.4.4-1-x86_64.pkg.tar.zst
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/windows/x86_64/hactool-1.4.0-3-x86_64.pkg.tar.xz
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/windows/x86_64/switch-tools-1.12.0-1-x86_64.pkg.tar.xz
            https://web.archive.org/web/https://pkg.devkitpro.org/packages/windows/x86_64/uam-1.1.0-2-x86_64.pkg.tar.xz

      - name: Ensure GITHUB_WORKSPACE directory is considered safe
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
        shell: msys2 {0}

      - name: Build
        run: |
          mv /mingw64/bin/python.exe /mingw64/bin/python.backup.exe
          ln -s /mingw64/bin/python2.exe /mingw64/bin/python.exe
          export PATH=$PATH:/mingw64/bin
          make -j3
        shell: msys2 {0}
